micronaut:
  application:
    name: pasalMn
netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/pasal
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: POSTGRES